name: Github actions demo
on: [push]

jobs:
    print-all-env:
        runs-on: ubuntu-latest
        steps:
            - name : print all envs 
              run: |
                  echo "GITHUB_ACTION = ${{ GITHUB_ACTION }}"
                  echo "GITHUB_ACTION_PATH = ${{ GITHUB_ACTION_PATH }}"
                  echo "GITHUB_ACTION_REPOSITORY = ${{ GITHUB_ACTION_REPOSITORY }}"
                  echo "GITHUB_ACTIONS = ${{ GITHUB_ACTIONS }}"
                  echo "GITHUB_ACTOR = ${{ GITHUB_ACTOR }}"
                  echo "GITHUB_ACTOR_ID = ${{ GITHUB_ACTOR_ID }}"
                  echo "GITHUB_API_URL = ${{ GITHUB_API_URL }}"
                  echo "GITHUB_BASE_REF = ${{ GITHUB_BASE_REF }}"
                  echo "GITHUB_ENV = ${{ GITHUB_ENV }}"
                  echo "GITHUB_EVENT_NAME = ${{ GITHUB_EVENT_NAME }}"
                  echo "GITHUB_EVENT_PATH = ${{ GITHUB_EVENT_PATH }}"
                  echo "GITHUB_GRAPHQL_URL = ${{ GITHUB_GRAPHQL_URL }}"
                  echo "GITHUB_HEAD_REF = ${{ GITHUB_HEAD_REF }}"
                  echo "GITHUB_JOB = ${{ GITHUB_JOB }}"
                  echo "GITHUB_OUTPUT = ${{ GITHUB_OUTPUT }}"
                  echo "GITHUB_PATH = ${{ GITHUB_PATH }}"
                  echo "GITHUB_REF = ${{ GITHUB_REF }}"
                  echo "GITHUB_REF_NAME = ${{ GITHUB_REF_NAME }}"
                  echo "GITHUB_REF_PROTECTED = ${{ GITHUB_REF_PROTECTED }}"
                  echo "GITHUB_REF_TYPE = ${{GITHUB_REF_TYPE}}"
                  echo "GITHUB_REPOSITORY = ${{GITHUB_REPOSITORY}}"
                  echo "GITHUB_REPOSITORY_ID = ${{GITHUB_REPOSITORY_ID}}"
                  echo "GITHUB_RUN_ID = ${{GITHUB_RUN_ID}}"
                  echo "GITHUB_RUN_NUMBER = ${{GITHUB_RUN_NUMBER}}"
                  echo "RUNNER_OS = ${{RUNNER_OS}}"        
        

            