name: Github actions demo
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
    checkout-source:
        runs-on: ubuntu-latest
        steps:
            - name : checkout 
              uses: actions/checkout@v4
              with:
                  ref: master
            - name: list files
              run: ls

            