name: Github actions demo
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
            - name : checkout 
              uses: actions/checkout@v4
              with:
                  ref: main
            - name: list files
              run: ls
    windows:
        runs-on: windows-latest
        steps:
          - name: checkout 
            uses: actions/checkout@v4
            with:
                ref: main
          - name : list files 
            run: ls
    print-all-env:
        runs-on: ubuntu-latest
        steps:
            - name : print all envs 
              run: echo {{ GITHUB_ACTOR }}
          
    

            